### PR TITLE
Fix conflict with Bootstrap theme.

### PR DESCRIPTION
**Pull request by gjb2048**
Fixes exactly what it says in the title!

### CODE REVIEW

**Comment by nadavkav** [comment]
Applied the patch, but still I am unable to view sub course pages (any module page)
 When I use XDEBUG I can see that 
echo $OUTPUT->header();
is calling bootstrap renderer and not elegance renderer :-(

**Comment by gjb2048** [comment]
Very odd!  I have no idea!

The lights are on but Julian is not home.

**Comment by nadavkav** [comment]
I am using latest Elegance and Bootstrap themes on latest moodle-org/master. Are you 2?

**Comment by gjb2048** [comment]
Yes and no.  Latest themes on M2.6.x.

**Pull request merged**
